### ISSUE TITLE
这个项目的报错问题

### ISSUE THREAD

**Issue by Charles-De-Geulle-Goah** [Li-TianCheng/test-case-generator#1]
请问为什么我把我自己写的C语言程序放进resource目录里面，运行测试程序，它会报错？报错如下：

guojia153@SKY-20220630LMK:~/tools/LTCgenerator$ python3 ./src/main.py --name addrspace.c
清理完成（0.322s）...
Traceback (most recent call last):
  File "./src/main.py", line 87, in <module>
    input, constraint = analysis(input_path)
  File "/home/guojia153/tools/LTCgenerator/src/gen_matrix.py", line 101, in analysis
    ast = parse_file(path)
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: ./resources/addrspace.c:3:41: before: *

**Comment by Li-TianCheng** [comment]
这个应该是pycparser这个库报的错，应该是python这个c语言解析库对c文件解析时出现错误，你可以检查一下你的c语言程序

**Comment by Li-TianCheng** [comment]
> 请问为什么我把我自己写的C语言程序放进resource目录里面，运行测试程序，它会报错？报错如下：
> 
> guojia153@SKY-20220630LMK:~/tools/LTCgenerator$ python3 ./src/main.py --name addrspace.c 清理完成（0.322s）... Traceback (most recent call last): File "./src/main.py", line 87, in input, constraint = analysis(input_path) File "/home/guojia153/tools/LTCgenerator/src/gen_matrix.py", line 101, in analysis ast = parse_file(path) File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/**init**.py", line 90, in parse_file return parser.parse(text, filename) File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 147, in parse return self.cparser.parse( File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 331, in parse return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc) File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack tok = call_errorfunc(self.errorfunc, errtoken, self) File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc r = errorfunc(token) File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 1931, in p_error self._parse_error( File "/home/guojia153/.local/lib/python3.8/site-packages/pycparser/plyparser.py", line 67, in _parse_error raise ParseError("%s: %s" % (coord, msg)) pycparser.plyparser.ParseError: ./resources/addrspace.c:3:41: before: *

这个应该是pycparser这个库报的错，应该是python这个c语言解析库对c文件解析时出现错误，你可以检查一下你的c语言程序
